FROM python:3.12-alpine

WORKDIR /app

COPY requirements-api.txt /app/

RUN pip install --no-cache-dir -r requirements-api.txt

COPY backend /app/backend
COPY shared /app/shared

EXPOSE 8000

CMD ["uvicorn", "backend.api:app", "--host", "0.0.0.0", "--port", "8000"]

