CATEGORIES = {
    "Намирници": ['Брашно', 'Додатоци за јадења', 'Додатоци за конзервирање', 'Готови оброци', 'Јајца',
                  'Кечап и сос од домати', 'Квасец', 'Мајонез, сенф, рен, преливи, сосови', 'Маргарин',
                  'Мешавина од зачини', 'Зрнести производи', 'Пудинг и шлаг', 'Шеќер', 'Оцет', 'Сол', 'Пекара',
                  'Супи и чорби', 'Сè за торти и колачи', 'Тестенини', 'Тортиљи', 'Масло', 'Зачини', 'Пире'],
    "Здрава храна": ['Безглутенски производи', 'Растителни напитоци', 'Експандиран ориз', 'Интегрален ориз',
                     'Интегрални колачи', 'Мед', 'Овесна каша', 'Снегулки и мусли', 'Солени грицки', 'Шумливи таблети',
                     'Семки и семки со лушпа', 'Суви овошја', 'Засладувачи', 'Здрави намази',
                     'Здрави грицки и пијалоци', 'Двопек', 'Протеин од сурутка', 'Зрнести производи'],
    "Млечни производи": ['Млеко', 'Јогурт', 'Путер', 'Млечни десерти', 'Млечни пијалоци', 'Кисело млеко',
                         'Кисела павлака', 'Грчки јогурт', 'Сирења', 'Намази од сирење', 'Сурутка',
                         'Преработено сирење', 'Овошен јогурт'],
    "Овошје и зеленчук": ['Зеленчук', 'Овошје', 'Конзервиран зеленчук', 'Конзервирано овошје'],
    "Месо и риба": ['Колбаси', 'Конзервирани производи', 'Намази', 'Паштета', 'Сувомеснато и процесирано месо',
                    'Салама', 'На тенки парчиња', 'Свежа риба', 'Свежо месо', 'Виршли и колбасици'],
    "Замрзнато": ['Готови сладоледи', 'Риба и морска храна', 'Замрзнат зеленчук', 'Замрзнато тесто и пецива',
                  'Замрзнато овошје', 'Замрзнато месо', 'Пици', 'Готови оброци'],
    "Пијалоци": ['Вода', 'Кафе', 'Газирани сокови', 'Капсули за кафе', 'Енергетски пијалоци', 'Чаеви', 'Ладени чаеви',
                 'Негазирани сокови'],
    "Алкохолни пијалоци": ['Пиво', 'Јаки алкохолни пијалоци', 'Вино', 'Витамински пијалоци', 'Квас', 'Коктел',
                           'Шампањско и пенливо вино'],
    "Слатки и грицки": ['Бонбони', 'Бонбоњера', 'Чоколади', 'Чоколадни барови', 'Десерти', 'Додатоци за млеко',
                        'Грицки', 'Кекс, вафли, бисквит', 'Кремови', 'Кроасани', 'Наполитанки', 'Ролати',
                        'Гуми за џвакање', 'Слатки намази', 'Диетални и здрави слатки'],
    "Лична хигиена и козметика": ['Сапуни', 'Чистење на лицето', 'Бричеви', 'Боја за коса', 'Гелови за туширање',
                                  'Хигиена за жени', 'Дезодоранси', 'Нега за коса', 'Нега на лице', 'Нега на раце',
                                  'Нега на стапала', 'Нега за тело', 'Орална хигиена', 'Хартија конфекција',
                                  'Препарати за сончање', 'Стик и рол-он', 'Сетови за поклон', 'Лабело',
                                  'Производи за бричење', 'Стапчиња за уши', 'Кондоми', 'Парфеми'],
    "Домашна хемија": ['Детергент за садови', 'Дополнителна нега на алишта', 'Инсектициди', 'Капсули за перење алишта',
                       'Марамчиња за перење алишта', 'Омекнувач за алишта', 'Прашок за перење алишта',
                       'Течни детергенти за перење алишта', 'Освежувачи на простор', 'Машинско миење садови',
                       'Средства за чистење', 'Средства за чистење на домаќинство', 'Средства за чистење на санитарии',
                       'Нега на обувки', 'Освежувачи на тоалет', 'Опрема за чистење'],
    "Катче за бебиња": ['Детска хигиена', 'Храна за бебиња', 'Каша за деца', 'Пијалоци', 'Пелени',
                        'Замена за млеко за деца', 'Играчки', 'Останато'],
    "Домашни миленици": ['Антипаразитски лекови', 'Влажна храна за мачки', 'Влажна храна за кучиња', 'Грицки за мачки',
                         'Грицки за кучиња', 'Сува храна за мачки', 'Сува храна за кучиња', 'Играчки за миленици', 'Останато'],
    "Дом и градина": ['Салфети', 'Кујнски прибор и садови', 'Сијалици', 'Батерии', 'Супер лепак', 'Чепкалки за заби', 'Свеќи', 'Останато'],
    "Цигари": ['Цигари и никотински производи'],
    "Облека": ['Облека за жени', 'Облека за мажи', 'Облека за деца', 'Чорапи и хулахопки', 'Пижами и долна облека'],
    "Разно": ['Останато', 'Плажа и базен', 'Канцелариски материјал', 'Текстил за дома', 'Кеси и фолија']
}

TAXONOMY_COMPRESSED = "\n".join([
    f"{main}: {', '.join(subs)}"
    for main, subs in CATEGORIES.items()
])

kipper_links = [
    # 'https://kipper.mk/mk/kipper-163-tetove/',
    # 'https://kipper.mk/mk/kipper-162-sveti-nikole/',
    'https://kipper.mk/mk/kipper-161-studenican/',
    # 'https://kipper.mk/mk/kipper-160-prilep/',
    # 'https://kipper.mk/mk/kipper-158-diber/',
    # 'https://kipper.mk/mk/kipper-157-nikushtak-kumanove/',
    # 'https://kipper.mk/mk/kipper-156-gostivar/',
    # 'https://kipper.mk/mk/kipper-155-kocani-2/',
    # 'https://kipper.mk/mk/kipper-154-strumice/',
    # 'https://kipper.mk/mk/kipper-153-strumice/',
    # 'https://kipper.mk/mk/kipper-152-kallnik/',
    # 'https://kipper.mk/mk/kipper-151-vinice/',
    'https://kipper.mk/mk/kipper-150-skopje-zelezara/',
    'https://kipper.mk/mk/kipper-149-shkup-butel/',
    # 'https://kipper.mk/mk/kipper-134-kumanove/',
    'https://kipper.mk/mk/kipper-147-shkup-maxhari/',
    # 'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-146-%d1%81%d1%82%d1%80%d1%83%d0%bc%d0%b8%d1%86%d0%b0/',
    # 'https://kipper.mk/mk/kipper-145-saraj/',
    # 'https://kipper.mk/mk/kipper-144-gostivar/',
    'https://kipper.mk/mk/kipper-141-petrovec/',
    # 'https://kipper.mk/mk/kipper-140-tetove/',
    # 'https://kipper.mk/mk/kipper-139-negotino/',
    # 'https://kipper.mk/mk/kipper-138-dellceve/',
    # 'https://kipper.mk/mk/kipper-137-probishtip/',
    # 'https://kipper.mk/mk/kipper-136-radiovce/',
    # 'https://kipper.mk/mk/kipper-135-gostivar/',
    'https://kipper.mk/mk/kipper-134-shkup/',
    'https://kipper.mk/mk/kipper-133-haracine/',
    # 'https://kipper.mk/mk/kipper-132-tetove/',
    # 'https://kipper.mk/mk/kipper-131struge/',
    # 'https://kipper.mk/mk/kipper-130-gradec-gostivar/',
    # 'https://kipper.mk/mk/kipper-129-strumice/',
    'https://kipper.mk/mk/kipper-128-kisela-vode/',
    'https://kipper.mk/mk/kipper-127-shkup/',
    'https://kipper.mk/mk/kipper-126-shkup/',
    # 'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-125-%d1%82%d0%b5%d1%82%d0%be%d0%b2%d0%be/',
    # 'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-124-%d0%b1%d0%b8%d1%82%d0%be%d0%bb%d0%b0/',
    # 'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-123-%d1%82%d0%b5%d1%82%d0%be%d0%b2%d0%be/',
    # 'https://kipper.mk/mk/kipper-122-llaskarce/',
    # 'https://kipper.mk/mk/kipper-121-kriva-palank/',
    'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-120-%d1%81%d0%ba%d0%be%d0%bf%d1%98%d0%b5/',
    'https://kipper.mk/mk/%d0%bc%d0%b0%d1%80%d0%ba%d0%b5%d1%82-119-%d1%81%d0%ba%d0%be%d0%bf%d1%98%d0%b5/',
    # 'https://kipper.mk/mk/kipper-118-struge/',
    # 'https://kipper.mk/mk/kipper-117-strumice/',
    # 'https://kipper.mk/mk/kipper-116-prilep/',
    # 'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-115-%d0%b1%d0%b8%d1%82%d0%be%d0%bb%d0%b0/',
    # 'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-114-%d1%82%d0%b5%d1%82%d0%be%d0%b2%d0%be/',
    'https://kipper.mk/mk/kipper-113-shkup/',
    # 'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-112-%d1%81%d0%ba%d0%be%d0%bf%d1%98%d0%b5/',
    # 'https://kipper.mk/mk/kipper-111-gostivar/',
    'https://kipper.mk/mk/kipper-110-draceve/',
    # 'https://kipper.mk/mk/kipper-109-strumice/',
    # 'https://kipper.mk/mk/kipper-108-tetovo/',
    'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-107-%d1%81%d0%ba%d0%be%d0%bf%d1%98%d0%b5/',
    # 'https://kipper.mk/mk/kipper-106-kumanove/',
    # 'https://kipper.mk/mk/kipper-105-manastir/',
    # 'https://kipper.mk/mk/kipper-104-gjevgjeli/',
    # 'https://kipper.mk/mk/kipper-103-prilep/',
    # 'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-102-%d0%ba%d1%83%d0%bc%d0%b0%d0%bd%d0%be%d0%b2%d0%be/',
    # 'https://kipper.mk/mk/kipper-101-oher/',
    'https://kipper.mk/mk/kipper-100-shkup/',
    'https://kipper.mk/mk/kipper-99-shkup/',
    # 'https://kipper.mk/mk/kipper-98-shtip/',
    # 'https://kipper.mk/mk/kipper-97-diber/',
    # 'https://kipper.mk/mk/kipper-96-valandove/',
    # 'https://kipper.mk/mk/kipper-95-tetove/',
    'https://kipper.mk/mk/kipper-94-shkup/',
    # 'https://kipper.mk/mk/kipper-93-zheline/',
    'https://kipper.mk/mk/kipper-92-shkup/',
    'https://kipper.mk/mk/kipper-91-shkup/',
    'https://kipper.mk/mk/kipper-90-shkup/',
    # 'https://kipper.mk/mk/kipper-089-prilep/',
    # 'https://kipper.mk/mk/kipper-88-veles/',
    'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-87-%d1%81%d0%b0%d1%80%d0%b0%d1%98/',
    # 'https://kipper.mk/mk/kipper-86-veles/',
    # 'https://kipper.mk/mk/kipper-85-manastir/',
    # 'https://kipper.mk/mk/kipper-84-struge/',
    # 'https://kipper.mk/mk/kipper-83-kumanove/',
    # 'https://kipper.mk/mk/kipper-82-shtip/',
    'https://kipper.mk/mk/kipper-81-shkup/',
    'https://kipper.mk/mk/kipper-80-aerodrom/',
    # 'https://kipper.mk/mk/kipper-79-oher/',
    # 'https://kipper.mk/mk/kipper-78-tetove/',
    # 'https://kipper.mk/mk/kipper-77-strumice/',
    'https://kipper.mk/mk/kipper-76-maxhari/',
    # 'https://kipper.mk/mk/kipper-75-kumanove/',
    # 'https://kipper.mk/mk/kipper-74-bervenice/',
    'https://kipper.mk/mk/%d0%ba%d0%b8%d0%bf%d0%bf%d0%b5%d1%80-073-%d1%81%d0%ba%d0%be%d0%bf%d1%98%d0%b5/',
    'https://kipper.mk/mk/kipper-72/',
    # 'https://kipper.mk/mk/kipper-71-likove/',
    # 'https://kipper.mk/mk/kipper-70-radovish/',
    'https://kipper.mk/mk/kipper-69/',
    # 'https://kipper.mk/mk/kipper-68/',
    # 'https://kipper.mk/mk/kipper-67/',
    # 'https://kipper.mk/mk/kipper-66/',
    # 'https://kipper.mk/mk/kipper-65/',
    # 'https://kipper.mk/mk/kipper-64/',
    # 'https://kipper.mk/mk/kipper-63/',
    # 'https://kipper.mk/mk/kipper-62/',
    # 'https://kipper.mk/mk/kipper-61/',
    # 'https://kipper.mk/mk/kipper-60/',
    # 'https://kipper.mk/mk/kipper-59/',
    # 'https://kipper.mk/mk/kipper-58/',
    # 'https://kipper.mk/mk/kipper-57/',
    # 'https://kipper.mk/mk/kipper-56/',
    # 'https://kipper.mk/mk/kipper-55/',
    # 'https://kipper.mk/mk/kipper-54/',
    'https://kipper.mk/mk/kipper-53/',
    'https://kipper.mk/mk/kipper-52/',
    'https://kipper.mk/mk/kipper-51/',
    # 'https://kipper.mk/mk/kipper-50/',
    # 'https://kipper.mk/mk/kipper-49/',
    # 'https://kipper.mk/mk/kipper-48/',
    # 'https://kipper.mk/mk/kipper-47/',
    # 'https://kipper.mk/mk/kipper-46/',
    # 'https://kipper.mk/mk/kipper-45/',
    # 'https://kipper.mk/mk/kipper-44/',
    # 'https://kipper.mk/mk/kipper-43/',
    # 'https://kipper.mk/mk/kipper-42/',
    # 'https://kipper.mk/mk/kipper-41/',
    # 'https://kipper.mk/mk/kipper-40/',
    # 'https://kipper.mk/mk/kipper-39/',
    # 'https://kipper.mk/mk/kipper-38/',
    'https://kipper.mk/mk/kipper-37/',
    # 'https://kipper.mk/mk/kipper-36/',
    'https://kipper.mk/mk/kipper-35/',
    'https://kipper.mk/mk/kipper-34/',
    'https://kipper.mk/mk/kipper-33/',
    'https://kipper.mk/mk/kipper-32/',
    'https://kipper.mk/mk/kipper-31/',
    'https://kipper.mk/mk/kipper-30/',
    'https://kipper.mk/mk/kipper-29/',
    'https://kipper.mk/mk/kipper-28/',
    'https://kipper.mk/mk/kipper-27/',
    'https://kipper.mk/mk/kipper-26/',
    'https://kipper.mk/mk/kipper-25/',
    'https://kipper.mk/mk/kipper-24/',
    # 'https://kipper.mk/mk/kipper-23/',
    # 'https://kipper.mk/mk/kipper-22/',
    # 'https://kipper.mk/mk/kipper-21/',
    # 'https://kipper.mk/mk/kipper-20/',
    # 'https://kipper.mk/mk/kipper-19/',
    # 'https://kipper.mk/mk/kipper-18/',
    # 'https://kipper.mk/mk/kipper-17/',
    # 'https://kipper.mk/mk/kipper-16/',
    # 'https://kipper.mk/mk/kipper-15/',
    # 'https://kipper.mk/mk/kipper-14/',
    # 'https://kipper.mk/mk/kipper-13/',
    # 'https://kipper.mk/mk/kipper-12/',
    # 'https://kipper.mk/mk/kipper-11/',
    # 'https://kipper.mk/mk/kipper-10/',
    # 'https://kipper.mk/mk/kipper-9/',
    # 'https://kipper.mk/mk/kipper-8/',
    # 'https://kipper.mk/mk/kipper-7/',
    # 'https://kipper.mk/mk/kipper-6/',
    # 'https://kipper.mk/mk/kipper-5/',
    # 'https://kipper.mk/mk/kipper-4/',
    # 'https://kipper.mk/mk/kipper-3/',
    # 'https://kipper.mk/mk/kipper-2/',
    # 'https://kipper.mk/mk/kipper-1/'
]